name: CI/CD Workflow
on:
  workflow_dispatch:
  push:
      branches:
       - dev
       - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4 
      with:
        node-version: '22.9.0'
        
    - name: Cache node modules 
      uses: actions/cache@v4
      with:
        path: ~/AppData/Roaming/npm-cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: Install dependencies 
      run: npm ci 
      
    - name: Build
      run: npm run build
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}
        
    - name: Sync with S3
      run: aws s3 sync dist/ s3://${{ vars.BUCKET_NAME }} --delete
      
    - name: Invalidate CloudFront distribution
      uses: chetan/invalidate-cloudfront-action@v2.4
      env:
        DISTRIBUTION: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
        PATHS: '/*'